id: P009611
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:40:41.174795
source_metadata:
  id: bdr:W1KG6147
  title: ཡིད་ཅན་ཐར་པར་བགྲོད་པའི་ཐེམ་སྐས་རྒྱུན་མཁོའི་བདག་བསྐྱེད་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    5fea79fcf5ba4a799c83d77038fa4227:
      image_group_id: I1KG6215
      title: ''
      volume_number: 1
      total_pages: 334
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
