id: I7A2FCAA3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T20:32:28+00:00'
last_modified: '2022-06-08T12:15:22.527235+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6147
  title: ཡིད་ཅན་ཐར་པར་བགྲོད་པའི་ཐེམ་སྐས་རྒྱུན་མཁོའི་བདག་བསྐྱེད་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    517A:
      image_group_id: I1KG6215
      title: ''
      total_pages: 334
      order: 1
      base_file: 517A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
